name: Publish

on:
  push:
    tags:
      - 'v\d+.*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    environment: publish
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore Clojure deps from cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.m2/repository
          ~/.deps.clj
          ~/.gitlibs
        enableCrossOsArchive: true
        key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
        restore-keys: cljdeps-

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        bb: 'latest'
        cli: 'latest'

    - name: Deploy to clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: bb -ci-clojars-deploy

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bb -ci-github-create-release

    - name: Inform Cljdoc
      run: bb -ci-cljdoc-request-build
